### ISSUE TITLE
Minimal deployment example is outdated

### ISSUE THREAD

**Issue by CorvusPrudens** [SoTrxII/Pandora#7]
I ran into similar issues as discussed in #5. Here was my solution.

I was unable to get a local storage sidecar to work. Upon attempting a write, Pandora reports an unknown error. As such, I tried to use simple file system storage. As noted in #5, removing the `OBJECT_STORE_NAME` variable prevents the pandora process from starting:
```bash
Error: No matching bindings found for serviceIdentifier: Symbol(ObjectStore)
pandora                 |     at _validateActiveBindingCount (/app/node_modules/inversify/src/planning/planner.ts:113:15)
pandora                 |     at _getActiveBindings (/app/node_modules/inversify/src/planning/planner.ts:91:3)
pandora                 |     at _createSubRequests (/app/node_modules/inversify/src/planning/planner.ts:146:22)
pandora                 |     at plan (/app/node_modules/inversify/src/planning/planner.ts:240:5)
pandora                 |     at /app/node_modules/inversify/src/container/container.ts:623:25
pandora                 |     at Container._get (/app/node_modules/inversify/src/container/container.ts:574:37)
pandora                 |     at Container._getButThrowIfAsync (/app/node_modules/inversify/src/container/container.ts:580:25)
pandora                 |     at Container.get (/app/node_modules/inversify/src/container/container.ts:325:17)
pandora                 |     at Object.<anonymous> (/src/inversify.config.ts:183:17)
pandora                 |     at Module._compile (node:internal/modules/cjs/loader:1165:14)
```

This originates from the Pandora object's construction in `src/inversify.config.ts`. I replaced it with the following:
```ts
container
  .bind(TYPES.Pandora)
  .toConstantValue(
    new Pandora(
      container.get<() => Promise<Eris.Client>>(TYPES.ClientProvider),
      container.get<IUnifiedBotController>(TYPES.UnifiedController),
      container.get<IRecorderService>(TYPES.AudioRecorder),
      container.get<IRecordingStore>(TYPES.StateStore),
      objComponent ? container.get<IObjectStore>(TYPES.ObjectStore) : undefined,
      container.get<ILogger>(TYPES.Logger)
    )
  );
```
This resolved the above issue, but I'm sure there's a more proper way to handle it.

The recording directory bound to pandora_recordings in the compose script also seems outdated or incorrect:
```yaml
services:
# ...
  pandora:
  # ...
    volumes:
      - pandora_recordings:/rec
# ...
```
The directory used by pandora as storage for the recordings is `/app/rec`, not `/rec`.

Finally, I was unable to get it working using proper volumes instead of a simple, local bind mount. Maybe there was some unrelated issue with my setup. Here was my final working setup:

```
.
├── components
│   └── state-store.yml
└── docker-compose.yml
└── Pandora
```
`Pandora` here is the cloned repo with the noted change to `src/inversify.config.ts`.

```yaml
#./docker-compose.yml
version: "3.7"
services:
  # The bot itself, record into raw, unusable files
  pandora:
    image: pandora
    build:
      context: ./Pandora
    container_name: pandora
    restart: always
    environment:
      # Discord bot token
      - PANDORA_TOKEN=<DISCORD_TOKEN>
      # Prefix for text-based command
      - COMMAND_PREFIX=!
      # Dapr component for state storage
      - STORE_NAME=statestore
      - DAPR_HTTP_PORT=3500
      - DAPR_SERVER_PORT=50051
    volumes:
      - ./pandora_recordings:/app/rec
    networks:
      - discord_recordings
  # Dapr sidecar, defining runtime implementations
  pandora-dapr:
    image: "daprio/daprd:edge"
    container_name: pandora-dapr
    command:
      [
        "./daprd",
        "-app-id",
        "pandora",
        "--dapr-http-port",
        "3500",
        "--app-port",
        "50051",
        "--dapr-grpc-port",
        "50002",
        "--components-path",
        "/components",
      ]
    # In docker-compose, you have to provide components by sharing a volume
    # this is the dapr/components directory
    volumes:
      - "./components/:/components"
    depends_on:
      - pandora
    network_mode: "service:pandora"

  # Converts the raw files into audio files
  pandora-cooking-server:
    image: sotrx/pandora-cooking-server:2.4.4
    container_name: pandora-cooking-server
    ports:
      - "3004:3004"
    restart: always
    volumes:
      - ./pandora_recordings:/app/rec
    networks:
      - discord_recordings

  # State store
  redis:
    image: "redis:alpine"
    networks:
      - discord_recordings

# Default docker network doesn't always provide name resolution
# so we create a new one
networks:
  discord_recordings:
```

```yaml
#./components/state-store.yml
# A sample statestore component using Redis
# as a backend
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis:6379
    - name: redisPassword
      value: ""
```
I hope this helps!
